#!/usr/bin/env python3
"""
Inter-Norm Predictability (Specificity Analysis)

Tests whether model idiosyncrasies are structured by predicting one norm's
BLUPs/ratings from the remaining 13 norms using Ridge regression (5-fold CV).
Computes within-model and cross-model R², yielding specificity ratios.

Outputs (→ outputs/results/SPECIFICITY/):
  - {ratings,idiosyncrasy}_metrics_robust.csv   Ridge R² per (model, norm, predictor)
  - {ratings,idiosyncrasy}_coeffs_robust.csv    Ridge coefficients
  - {ratings,idiosyncrasy}_specificity.csv      Specificity ratios (within / cross-mean)

The publication figure (Panel B) is generated by LMM/06_combined_figure_publication.R,
which reads the specificity CSVs produced here.

Performance: Pre-pivots data into per-model numpy matrices before parallelization.

Usage:
    python -m src.analysis.SPECIFICITY.01_inter_norm_predictability --workers 64
"""

import pandas as pd
import numpy as np
import os
import time
import argparse
import warnings
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, cross_validate
from sklearn.pipeline import Pipeline
from typing import Dict, List, Tuple, Optional
from concurrent.futures import ProcessPoolExecutor, as_completed

from src.analysis.EXTENSION.utils import (
    load_model_norms_stochastic,
    compute_model_means,
    NORM_TO_HUMAN_COLUMN,
    ensure_results_dir,
    LMM_FULL_DIR
)

warnings.filterwarnings('ignore')

# === CONFIG ===
ALPHAS = [0.01, 0.1, 1.0, 10.0, 100.0]
MIN_SAMPLES = 50




def load_all_blups(norms: List[str]) -> pd.DataFrame:
    """Load BLUPs for all specified norms."""
    dfs = []
    for norm in norms:
        file_path = os.path.join(LMM_FULL_DIR, f"blups_{norm}.csv")
        if os.path.exists(file_path):
            df = pd.read_csv(file_path)
            df['norm'] = norm
            dfs.append(df)
        else:
            print(f"  Warning: BLUP file not found for {norm}")
    
    if not dfs:
        return pd.DataFrame()
    combined = pd.concat(dfs, ignore_index=True)
    print(f"  Loaded {len(norms)} norm files: {len(combined)} rows")
    return combined

# ──────────────────────────────────────────────────────────────────────
# Pre-pivoting: convert long DataFrame → dict of {model: 2D numpy array}
# ──────────────────────────────────────────────────────────────────────

def prepivot_data(df: pd.DataFrame, value_col: str, norms: List[str]):
    """
    Pre-pivot long data into per-model numpy matrices.
    
    Returns:
        model_matrices: dict {model_name: np.ndarray of shape (n_words, n_norms)}
        word_index:     dict {model_name: list of words (row order)}
        norm_index:     list of norms (column order)
    """
    model_matrices = {}
    word_index = {}
    norm_index = norms  # fixed column order
    
    for model, group in df.groupby('model'):
        # Use pivot_table (handles duplicates via mean) instead of pivot
        wide = group.pivot_table(index='word', columns='norm', values=value_col, aggfunc='mean')
        
        # Ensure all norms present (fill missing with NaN)
        for n in norms:
            if n not in wide.columns:
                wide[n] = np.nan
        
        wide = wide[norms]  # enforce column order
        
        model_matrices[model] = wide.values  # numpy array
        word_index[model] = wide.index.tolist()
        print(f"    {model}: {wide.shape[0]} words × {wide.shape[1]} norms, "
              f"NaN%={wide.isna().mean().mean():.1%}")
    
    return model_matrices, word_index, norm_index


def precompute_aggregate(model_matrices: dict, word_index: dict, 
                         norm_index: list, target_model: str) -> Tuple[np.ndarray, list]:
    """
    Pre-compute the aggregate baseline: mean of all other models' data,
    aligned to the target model's word set.
    """
    target_words = set(word_index[target_model])
    other_models = [m for m in model_matrices if m != target_model]
    
    if not other_models:
        return None, None
    
    # Find common words across target and all other models
    common = target_words.copy()
    for m in other_models:
        common = common.intersection(word_index[m])
    common = sorted(common)
    
    if len(common) < MIN_SAMPLES:
        return None, None
    
    # Stack and average
    arrays = []
    for m in other_models:
        idx_map = {w: i for i, w in enumerate(word_index[m])}
        rows = [idx_map[w] for w in common]
        arrays.append(model_matrices[m][rows])
    
    agg_matrix = np.mean(arrays, axis=0)  # (n_common, n_norms)
    return agg_matrix, common


# ──────────────────────────────────────────────────────────────────────
# Worker function: receives only numpy arrays, not DataFrames
# ──────────────────────────────────────────────────────────────────────

def run_ridge_task(args) -> Optional[Dict]:
    """
    Worker for a single Ridge regression task.
    
    Receives pre-sliced numpy arrays — no DataFrame serialization.
    """
    (target_model, predictor_label, target_norm_idx, 
     X_data, y_data, predictor_norms, target_norm_name, analysis_type) = args
    
    if X_data is None or y_data is None:
        return None
    if len(y_data) < MIN_SAMPLES:
        return None
    
    # Clean NaNs
    valid = ~np.isnan(X_data).any(axis=1) & ~np.isnan(y_data)
    if valid.sum() < MIN_SAMPLES:
        return None
    
    X = X_data[valid]
    y = y_data[valid]
    
    # Train RidgeCV
    n_splits = min(5, len(X) // 10)
    if n_splits < 2:
        n_splits = 2
    
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('ridge', RidgeCV(alphas=ALPHAS))
    ])
    
    cv_results = cross_validate(pipeline, X, y, cv=kf, scoring='r2', return_estimator=True)
    
    # Extract coefficients
    coeffs_sum = np.zeros(X.shape[1])
    alpha_sum = 0.0
    for est in cv_results['estimator']:
        ridge = est.named_steps['ridge']
        coeffs_sum += ridge.coef_
        alpha_sum += ridge.alpha_
    
    avg_coeffs = coeffs_sum / n_splits
    avg_alpha = alpha_sum / n_splits
    
    result = {
        'target_model': target_model,
        'predictor_model': predictor_label,
        'target_norm': target_norm_name,
        'analysis_type': analysis_type,
        'prediction_type': 'within' if target_model == predictor_label else 'cross',
        'r2_mean': cv_results['test_score'].mean(),
        'r2_std': cv_results['test_score'].std(),
        'n_samples': len(X),
        'alpha_mean': avg_alpha,
    }
    
    for name, val in zip(predictor_norms, avg_coeffs):
        result[f"coeff_{name}"] = val
    
    return result


# ──────────────────────────────────────────────────────────────────────
# Pipeline orchestrator
# ──────────────────────────────────────────────────────────────────────

def prepare_task_args(target_model, predictor_label, target_norm_idx, target_norm,
                      pred_matrix, pred_words, target_matrix, target_words,
                      norms, analysis_name):
    """Prepare aligned numpy arrays for a single task.
    
    Drops predictor columns that are entirely NaN (e.g., missing BLUP files).
    """
    other_norm_indices = [i for i in range(len(norms)) if i != target_norm_idx]
    predictor_norms = [norms[i] for i in other_norm_indices]
    
    # Get common words
    pred_word_set = set(pred_words)
    target_word_map = {w: i for i, w in enumerate(target_words)}
    pred_word_map = {w: i for i, w in enumerate(pred_words)}
    
    common = [w for w in target_words if w in pred_word_set]
    if len(common) < MIN_SAMPLES:
        return None
    
    t_rows = [target_word_map[w] for w in common]
    p_rows = [pred_word_map[w] for w in common]
    
    y = target_matrix[t_rows, target_norm_idx]
    X_full = pred_matrix[np.ix_(p_rows, other_norm_indices)]
    
    # Drop predictor columns that are entirely NaN (missing norm data)
    col_valid = ~np.isnan(X_full).all(axis=0)
    if col_valid.sum() == 0:
        return None
    
    X = X_full[:, col_valid]
    predictor_norms = [predictor_norms[i] for i in range(len(predictor_norms)) if col_valid[i]]
    
    # Also check target
    if np.isnan(y).all():
        return None
    
    return (target_model, predictor_label, target_norm_idx,
            X, y, predictor_norms, target_norm, analysis_name)


def run_inter_norm_pipeline(df: pd.DataFrame, analysis_name: str,
                           value_col: str, norms: List[str],
                           workers: int = 4) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Optimized pipeline: pre-pivots then parallelizes Ridge tasks."""
    
    t0 = time.time()
    
    # 1. Pre-pivot
    print(f"  Pre-pivoting data for {analysis_name}...")
    model_matrices, word_index, norm_index = prepivot_data(df, value_col, norms)
    models = sorted(model_matrices.keys())
    print(f"  Pre-pivoted {len(models)} models × {len(norms)} norms in {time.time()-t0:.1f}s")
    
    # 2. Pre-compute aggregate baselines (one per target model)
    print(f"  Pre-computing aggregate baselines...")
    t1 = time.time()
    agg_matrices = {}
    agg_words = {}
    for target_model in models:
        agg_m, agg_w = precompute_aggregate(model_matrices, word_index, norm_index, target_model)
        agg_matrices[target_model] = agg_m
        agg_words[target_model] = agg_w
    print(f"  Aggregates computed in {time.time()-t1:.1f}s")
    
    # 3. Build task arguments (compact numpy arrays only)
    print(f"  Building tasks...")
    tasks = []
    
    for target_model in models:
        for ni, target_norm in enumerate(norms):
            # Within-model
            args = prepare_task_args(
                target_model, target_model, ni, target_norm,
                model_matrices[target_model], word_index[target_model],
                model_matrices[target_model], word_index[target_model],
                norms, analysis_name)
            if args: tasks.append(args)
            
            # Aggregate cross-model
            if agg_matrices[target_model] is not None:
                args = prepare_task_args(
                    target_model, 'AGGREGATE', ni, target_norm,
                    agg_matrices[target_model], agg_words[target_model],
                    model_matrices[target_model], word_index[target_model],
                    norms, analysis_name)
                if args: tasks.append(args)
            
            # Pairwise cross-model
            for pred_model in models:
                if pred_model != target_model:
                    args = prepare_task_args(
                        target_model, pred_model, ni, target_norm,
                        model_matrices[pred_model], word_index[pred_model],
                        model_matrices[target_model], word_index[target_model],
                        norms, analysis_name)
                    if args: tasks.append(args)
    
    print(f"  Built {len(tasks)} tasks, launching {workers} workers...")
    
    # 4. Execute
    t2 = time.time()
    results = []
    done = 0
    
    with ProcessPoolExecutor(max_workers=workers) as executor:
        futures = [executor.submit(run_ridge_task, t) for t in tasks]
        
        for future in as_completed(futures):
            res = future.result()
            if res:
                results.append(res)
            done += 1
            if done % 200 == 0:
                elapsed = time.time() - t2
                rate = done / elapsed
                eta = (len(tasks) - done) / rate if rate > 0 else 0
                print(f"    {done}/{len(tasks)} tasks ({rate:.0f}/s, ETA {eta:.0f}s)")
    
    exec_time = time.time() - t2
    total_time = time.time() - t0
    print(f"  Execution: {exec_time:.1f}s | Total: {total_time:.1f}s | {len(results)} results")
    
    # 5. Build output DataFrames
    print(f"  Results collected: {len(results)} (from {len(tasks)} tasks)")
    
    if not results:
        print("  ⚠ WARNING: No results returned! All tasks produced None.")
        return pd.DataFrame(), pd.DataFrame()
    
    all_df = pd.DataFrame(results)
    print(f"  DataFrame columns: {list(all_df.columns)}")
    
    meta_cols = ['target_model', 'predictor_model', 'target_norm', 'analysis_type', 
                 'prediction_type', 'r2_mean', 'r2_std', 'n_samples', 'alpha_mean']
    coeff_cols = [c for c in all_df.columns if c.startswith('coeff_')]
    
    metrics_df = all_df[meta_cols].copy()
    coeffs_df = all_df[meta_cols[:5] + coeff_cols].copy()
    
    return metrics_df, coeffs_df


def compute_specificity(metrics_df: pd.DataFrame) -> pd.DataFrame:
    """Compute specificity ratios from metrics."""
    within = metrics_df[metrics_df['predictor_model'] == metrics_df['target_model']][
        ['target_model', 'target_norm', 'r2_mean']
    ].rename(columns={'r2_mean': 'within_r2'})
    
    pairwise = metrics_df[
        (metrics_df['predictor_model'] != metrics_df['target_model']) & 
        (metrics_df['predictor_model'] != 'AGGREGATE')
    ]
    pairwise_mean = pairwise.groupby(['target_model', 'target_norm'])['r2_mean'].mean().reset_index()
    pairwise_mean = pairwise_mean.rename(columns={'r2_mean': 'cross_mean_r2'})
    
    agg = metrics_df[metrics_df['predictor_model'] == 'AGGREGATE'][
        ['target_model', 'target_norm', 'r2_mean']
    ].rename(columns={'r2_mean': 'aggregate_r2'})
    
    merged = pd.merge(within, pairwise_mean, on=['target_model', 'target_norm'], how='left')
    merged = pd.merge(merged, agg, on=['target_model', 'target_norm'], how='left')
    
    merged['spec_vs_pairwise'] = merged['within_r2'] / merged['cross_mean_r2']
    merged['spec_vs_aggregate'] = merged['within_r2'] / merged['aggregate_r2']
    
    return merged


def main():
    parser = argparse.ArgumentParser(description='Inter-Norm Predictability (Optimized)')
    parser.add_argument('--workers', type=int, default=4)
    parser.add_argument('--sample_n', type=int, default=None,
                        help='Limit to N unique words (for testing)')
    parser.add_argument('--nrows', type=int, default=None,
                        help='Read only first N rows per file (for testing)')
    args = parser.parse_args()
    
    results_dir = ensure_results_dir("SPECIFICITY")
    
    # Use all raw norms as-is — no pre-aggregation
    norms = sorted(list(NORM_TO_HUMAN_COLUMN.keys()))
    print(f"Norms for analysis ({len(norms)}): {norms}")
    
    t_start = time.time()
    
    # --- 1. RATINGS ---
    print("\n=== Analysis 1: Ratings (RidgeCV + Regularization) ===")
    raw_df = load_model_norms_stochastic(sample_n=args.sample_n, nrows=args.nrows)
    if not raw_df.empty:
        print(f"  Raw data: {len(raw_df):,} rows, {raw_df['model'].nunique()} models")
        means_df = compute_model_means(raw_df)
        del raw_df  # free ~8GB
        print(f"  Means: {len(means_df):,} rows")
        
        res_df, coeff_df = run_inter_norm_pipeline(
            means_df, "ratings", "mean_rating", norms, workers=args.workers)
        del means_df
        
        if not res_df.empty:
            res_df.to_csv(os.path.join(results_dir, "ratings_metrics_robust.csv"), index=False)
            coeff_df.to_csv(os.path.join(results_dir, "ratings_coeffs_robust.csv"), index=False)
            spec_df = compute_specificity(res_df)
            spec_df.to_csv(os.path.join(results_dir, "ratings_specificity.csv"), index=False)
            print(f"  ✅ Saved: metrics ({len(res_df)}), coeffs ({len(coeff_df)}), specificity ({len(spec_df)})")

    # --- 2. IDIOSYNCRASY ---
    print("\n=== Analysis 2: Idiosyncrasy (RidgeCV + Regularization) ===")
    blups_df = load_all_blups(norms)
    if not blups_df.empty:
        if args.sample_n:
            words = blups_df['word'].unique()
            if len(words) > args.sample_n:
                sampled = np.random.choice(words, args.sample_n, replace=False)
                blups_df = blups_df[blups_df['word'].isin(sampled)]
                print(f"  Sampled to {args.sample_n} words: {len(blups_df)} rows")
        
        res_idio, coeff_idio = run_inter_norm_pipeline(
            blups_df, "idiosyncrasy", "idiosyncrasy", norms, workers=args.workers)
        del blups_df
        
        if not res_idio.empty:
            res_idio.to_csv(os.path.join(results_dir, "idiosyncrasy_metrics_robust.csv"), index=False)
            coeff_idio.to_csv(os.path.join(results_dir, "idiosyncrasy_coeffs_robust.csv"), index=False)
            spec_idio = compute_specificity(res_idio)
            spec_idio.to_csv(os.path.join(results_dir, "idiosyncrasy_specificity.csv"), index=False)
            print(f"  ✅ Saved: metrics ({len(res_idio)}), coeffs ({len(coeff_idio)}), specificity ({len(spec_idio)})")
    
    total = time.time() - t_start
    print(f"\n=== All done in {total:.0f}s ({total/60:.1f}min). Run 04b/04c for plots. ===")

if __name__ == "__main__":
    main()
